### PR TITLE
Added Raise/Lower to build script

### PR DESCRIPTION
**Pull request by darrell-aevum**
I added a Raise and Lower user action when building.
The actions don't have icons like the Rotate and Cancel do.

### CODE REVIEW

**Comment by Wyqer** [comment]
A nice small additions, many thanks for your work.
It'll be merged in a "0.963-additions" branch, so others could "update" their 0.963 with some additional stuff, which was contributed after the release of 0.963.
Reason is, that the next version of Liberation (0.97) will have a fully rewritten and refactored codebase. Therefore current contributions won't be compatible to the new structure.

**Comment by darrell-aevum** [comment]
Sounds good. I had also added an action to have buildings adjust for slope, but I noticed you guys beat me to it. 

Is there an easy way to start the mission with resources, or add resources in game for development purposes?

**Comment by Wyqer** [comment]
// Run via debug console and execute local.

    // Crate with 100 supplies spawns at player position.
    [] call F_createCrate;

    // Crate with 100 ammo spawns at player position.
    [KP_liberation_ammo_crate] call F_createCrate;

    // Crate with 100 fuel spawns at player position.
    [KP_liberation_fuel_crate] call F_createCrate;

**Comment by darrell-aevum** [comment]
Great,
Thanks

**Pull request merged**
