### PR TITLE
auto restart server

### PR DESCRIPTION
**Pull request by k4s0**
this script auto restart the mission every 3hrs and use the liberation
notification system to inform players, you can use #restart or
#restartserver (Windows Dedicated Only this restrat the arma3server
process).
To Do:
add param to turn on/off the auto-restart
add param to set time until restart (1-3-6hrs)
if anyone want to help me :)

### CODE REVIEW

**Comment by Wyqer** [comment]
I'll merge it in a seperate branch. In this we can implement the parameters etc.
Thanks for the work. :)

**Comment by Applejakerie** [comment]
Suggesting a wait for player = 0 on the restart timers. I know it's kind of redundant but in some cases it'll give players the 10 more minutes they need to finish the sector they're prolonged on. Maybe after 30mins force the restart, players or no players.

**Comment by Wyqer** [comment]
This has to be another optional thing than. If you really wait until the players are disconnected it could mess up your time schedule for restarts on your server. Some admins might want direct restarts and some would like a "is really everyone gone" check. Personally I think the notifications which are starting 30 minutes prior to restart gives enough time to players to rearrange their current taskings.

**Comment by k4s0** [comment]
I've been playing the liberation since it's gone, and if I get the notification that within 30 min is the restart, I will not start capturing a big city but a small one because I know I can do. Said this thank you anyway for your opinion @Applejakerie 👍

**Comment by Applejakerie** [comment]
@Wyqer Can we not restart from the original restart time and not the extended, so the extended half hour makes no difference as the next restart counter is already underway? Definitely an optional thing tho.

@k4s0 Same here. 😄I'm not doubting the communities ability to cap a sector or anything, I'm more thinking like with my experience last night. We took a small sector in an easy 15-20 minutes, it was rather open and easy to clear from a distance. Once we'd moved in to secure tho we were hit with easily another 30 minutes of reinforcements and then forces trying to recapture. It would be a pain to miss out on that experience because of a restart that could of been put off by 30 minutes maybe. 😦 Maybe a better suggestion would be (as we can force with #restart) to have a #cancel that would cancel the restart this one time, no need to worry about timing or anything post-restart, just cancel it and have the game move on to the next restart timer. I'm sure admin or player voted admins can then use #restart when it is suitable?

**Pull request merged**
