### PR TITLE
Update 3cBAF.sqf

### PR DESCRIPTION
**Pull request by ChiefOwens**
Added new aircraft and uav from Jets DLC. Changed HURON to RHS_CH_47F so players can haul supplies by chopper.

### CODE REVIEW

**Comment by ChiefOwens** [comment]
Did not add new vehicles to elite_vehicles as I see the other commits do not have them there as well.

**Comment by Applejakerie** [comment]
```
	["B_Heli_Transport_03_F", -7.5, [0,2.2,-1], [0,0.5,-1], [0,-1.2,-1]],
	["B_Heli_Transport_03_unarmed_F", -7.5, [0,2.2,-1], [0,0.5,-1], [0,-1.2,-1]],
```

Huron can definitely load and lift cargo?

**Comment by Applejakerie** [comment]
I'll add the jets and uav to the other 5 presets with my updates for the last 3 presets coming tonight, maybe tomorrow morning. I'll add them to the elite list too if you want me to add them here as well Chief.

**Comment by ChiefOwens** [comment]
I don't know what you guys are doing with the carrier so I didn't add them either. Kind of trying to follow along with what you guys are doing with the preset so its standard(ish) across the board. 3cb BAF depends on air assets because there is no armor which is how I designed it to be. It's hard, but the players have more resources for air. Just add water and pilots. =)

**Comment by Applejakerie** [comment]
Well the last edits are going in by myself tonight or tomorrow, I'll make sure we're on the same standard format don't worry. :))

**Comment by ChiefOwens** [comment]
Closing and reopening new one with different information.

**Pull request closed without merging**
