### PR TITLE
Fixed props saving incorrectly and buildmenu obstructions

### PR DESCRIPTION
**Pull request by Cre8or**
**When merged this pull request will:**
- fix objects not saving/respawning in the exact position they were left at - this has been an issue for the longest time and caused player-built FOBs to scramble slightly after a savegame reload, sometimes moving props up to a few meters away from their original spawn location
- fix the building menu from detecting ground items (magazines, mags, uniforms, etc.) aswell as corpses as obstructions when attempting to build vehicles or logistics items

**Note:** due to the fixes done to the save manager, the savegame format will change slightly, in that the buildings data now holds 2 vectors for an object's orientation (`vectorDirVisual` and `vectorUpVisual` for use in `setVectorDirAndUp`) rather than 1 vector (`vectorUp`?) and 1 number (`getDir`). However, **old savegame formats are fully supported** - the code is reverse compatible and will convert old formats into the new one upon loading into the mission. No further changes are required.

### CODE REVIEW

**Comment by Wyqer** [comment]
Sounds really great, many thanks for this.
Just have a look at the review comment. Without at proper commit where the changes inside the code are really visible it's hard to review. Currently it's all showing as "everything deleted" and "everything added".
How did you get the idea concerning using two vectors? Your test were all successful?
I haven't tested your request until now, but if this really fixes the annoying misplacement behaviour which was always in Liberation it would be a really great addition and many thanks for the willingnes to share it for the official version. 👍

**Comment by Cre8or** [comment]
I believe the changes viewer isn't working because Atom was set to use LF while the original text files were using CRLF. Going to reupload them and see if that fixes it.

As for using 2 vectors - I've done a bit of debug console testing on a vehicle to figure this out. My idea was if I could find a way to move an object to its own position and its own orientation, and the object doesn't move/rotate at all, then my code would be suited for saving/loading player-built structures.
The first thing I noticed is that `getPos`, `getPosATL` and `getPosASL` are all orientation sensitive. You can test this by simply doing: `cursorTarget setPosATL (getPosATL cursorTarget)` on something like a car that is parked on a slope, and it will move slightly everytime the command is executed. The steeper the incline, the more the object will move.

I discussed this issue with some people on the ArmA 3 Discord and learned that those commands use a position that isn't "on the ground", but rather somewhere in the middle of the object's bounding box (roughly). Now, if the object is tilted, the position by those functions is offset relative to the surface's normal (to which the object is aligned). The fix for this was to use getPosWorld, which is unaffected by object orientation.

As for the orientation itself; applying an object's up vector and its direction (as a number) to set its orientation wasn't reliable enough. There were cases where the object rotated slightly when the command was executed, with the amount of rotation depending on the direction (the object stabilises around the 0°-direction (North)). I thought about this some more and realised that if I had an object that was facing straight up, there might be a "gimbal lock"-esque type of situation where setting the direction wouldn't work at all anymore, though admittedly I didn't test this theory. Instead I looked at how other popular mods and gamemodes save their data and it seems the common consensus is `setVectorDirAndUp` which seems completely failsafe, as you can achieve any orientation in a 3D environment using 2 vectors (since the remaining vector can always be determined using cross product).

Anyhow, I'm going to work on fixing these previews today so that we can (hopefully) get this merged soon. In the meantime, here's two pictures which I took after saving, ending and then reloading the mission in local multiplayer:
https://cdn.discordapp.com/attachments/227027935142477834/428201088299302912/20180327163700_1.jpg
https://cdn.discordapp.com/attachments/227027935142477834/428201334353690624/20180327163711_1.jpg

(yes, I intentionally left that car on there 😉)

**Comment by Wyqer** [comment]
Sounds great and now it seems like a really consistent explanation for the cause of the issue and a way to prevent it. Many thanks for the great and complete explanation. I really appreciate the time you spent for this.
Maybe you should also think about joining the Liberation Discord (link in the readme), so we could have a further talk about this issue.

With the tanks DLC there will be a small update on the current build of Liberation with the new tanks and propably all the current "addition" stuff. But afterwards it'll be legacy and many things will be different after 0.97. But no reliable deadline for the refactoring currently.
Just as a heads up, that 0.963 and lower will get deprecated this year.

**Comment by Cre8or** [comment]
Noted. I'll hop on the Discord later today.

Also done reuploading the files in the correct newline type, the changes should now be visible.

**Pull request merged**
